name: E2E Stage Tests

on:
  push:
  schedule:
    - cron: '0 3 * * *'

jobs:
  cypress-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          browser: chrome
        continue-on-error: true
      - name: Copy test execution videos
        run: |
          mkdir public
          ls cypress/videos
          cp -r cypress/videos public/videos
      - name: Merge test results into one
        run: npm run report:merge
      - name: Generate HTML report
        run: npm run report:generate
      - name: Deploy report page
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          user_name: 'git config user.name'
          user_email: 'git config user.email'